name: ArtiPedia - Web Referensi Pendidikan
description: ArtiPedia - Web Referensi Pendidikan - berisi informasi tentang Pengertian, Definisi, Istilah, Referensi, Tutorial, Buku, RPP, dan Berita lainnya terkait dengan pendidikan.
url: https://artipedia.github.io/NewArtiPedia/
repository: "ArtiPedia/NewArtiPedia"
timezone: Asia/Jakarta

twitter:
  username: artipedia243
  
disqus:
  shortname: ArtiPedia
  
logo: "/img/logo-2x.png"
image: {{page.image}}
google_analytics_id: UA-115101359-3
google_site_verification: C1hGxjtzZwOcieGwAnCwFYFX2eSEVxz_JWWiytICEEc

authors:
    artipedia:
      name:           you
      slug:           you
      site:           https://coinsprices.net
      avatar:         /img/you.png
      avatarlow:      /img/low/you.jpg
      bio:            "Hi, I am wahyu, the owner https://artipeda.id, https://www.livecointrackers.com, dan https://coinsprices.net, Website Crypto Currency "
      email:          wahyu243@gmail.com 
      twitter:        wahyu37853583
      facebook:       you.w4hyou

collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
  posts:
    permalink: "/wiki/:title.html"
    output: true
  tutorials:
    output: true
    
defaults:
- scope:
    path: _docs
    type: docs
  values:
    layout: docs
- scope:
    path: _posts
    type: posts
  values:
    layout: news_item
    image: twitter-card.png
    author: you
    avatar: /img/you.jpg
    
plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-mentions
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jemoji
- jekyll-paginate

sass:
  style: compressed
  
exclude:
- ".gitignore"
- CNAME
- icomoon-selection.json
- readme.md

compress_html:
  clippings: all
  comments: [""]
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []
    
paginate: 16
paginate_path: /page/:num/
  
include: ['.htaccess']
