name: ArtiPedia - Web Referensi Pendidikan
description: ArtiPedia - Web Referensi Pendidikan - berisi informasi tentang Pengertian, Definisi, Istilah, Referensi, Tutorial, Buku, RPP, dan Berita lainnya terkait dengan pendidikan.
url: https://artipedia.id
repository: "ArtiPed/NewArtiPedia"
timezone: Asia/Jakarta
logo: logo-2x.png

twitter:
  username: artipedia243

disqus:
  shortname: ArtiPedia

logo: "/img/logo-2x.png"

image: {{page.image}}

adsense_id: ca-pub-1344864982877041

google_analytics_id: UA-115101359-3

google_site_verification: C1hGxjtzZwOcieGwAnCwFYFX2eSEVxz_JWWiytICEEc

authors:
    artipedia:
      name:           you
      slug:           you
      site:           https://coinsprices.net
      avatar:         /img/you.png
      avatarlow:      /img/low/you.jpg
      bio:            "Hi, I am wahyu, the owner https://artipeda.id, https://www.livecointrackers.com, dan https://coinsprices.net, Website Crypto Currency "
      email:          wahyu243@gmail.com 
      twitter:        wahyu37853583
      facebook:       you.w4hyou

collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
  posts:
    permalink: "/:categories/:title"
    output: true
  tutorials:
    output: true

defaults:
- scope:
    path: _docs
    type: docs
  values:
    layout: docs
- scope:
    path: _posts
    type: posts
  values:
    layout: news_item
    image: twitter-card.png
    author: artipedia
    avatar: /img/you.jpg
- scope:
    path: _posts/buku
    type: posts
  values:
    layout: news_item
    category: buku
    image: twitter-card.png
    author: artipedia
    avatar: /img/you.jpg
    read_time: true
    comments: true
    support: true
    breadcrumbs:
      - label: "Buku"
        url: /buku/
- scope:
    path: _posts/artikel
    type: posts
  values:
    layout: news_item
    category: artikel
    image: twitter-card.png
    author: artipedia
    avatar: /img/you.jpg
    read_time: true
    comments: true
    support: true
    breadcrumbs:
      - label: "Artikel"
        url: /artikel/
- scope:
    path: _posts/berita
    type: posts
  values:
    layout: news_item
    category: berita
    image: twitter-card.png
    author: artipedia
    avatar: /img/you.jpg
    read_time: true
    comments: true
    support: true
    breadcrumbs:
      - label: "Berita"
        url: /berita/
- scope:
    path: _posts/materi
    type: posts
  values:
    layout: news_item
    category: materi
    image: twitter-card.png
    author: artipedia
    avatar: /img/you.jpg
    read_time: true
    comments: true
    support: true
    breadcrumbs:
      - label: "Materi"
        url: /materi/
- scope:
    path: _posts/soal
    type: posts
  values:
    layout: news_item
    category: soal
    image: twitter-card.png
    author: artipedia
    avatar: /img/you.jpg
    read_time: true
    comments: true
    support: true
    breadcrumbs:
      - label: "Soal"
        url: /soal/
- scope:
    path: _posts/teori
    type: posts
  values:
    layout: news_item
    category: teori
    image: twitter-card.png
    author: artipedia
    avatar: /img/you.jpg
    read_time: true
    comments: true
    support: true
    breadcrumbs:
      - label: "Teori"
        url: /teori/
- scope:
    path: _posts/rpp
    type: posts
  values:
    layout: news_item
    category: rpp
    image: twitter-card.png
    author: artipedia
    avatar: /img/you.jpg
    read_time: true
    comments: true
    support: true
    breadcrumbs:
      - label: "RPP"
        url: /rpp/

plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-mentions
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jemoji
- jekyll-paginate

sass:
  style: compressed

exclude:
- ".gitignore"
- CNAME
- icomoon-selection.json
- readme.md

compress_html:
  clippings: all
  comments: [""]
  endings: [all]
  profile: false
  blanklines: false
  ignore:
    envs: []
    
paginate: 16
paginate_path: /page/:num/
  
include: [.htaccess, _redirects]
